sonar.projectKey=KevinHidalgoDS_tfm-analitica
sonar.projectName=tfm-analitica
sonar.organization=kevinhidalgods

# Ruta al código fuente
sonar.sources=src/
sonar.exclusions=\
**/__init__.py,\
**/__pycache__/**,\
**/.venv/**,\
**/.pytest_cache/**,\
**/site/**,\
**/build/**

# Ruta a los tests
sonar.tests=tests/

sonar.python.version=3.14

# Aquí se puede especificar la ruta al reporte de cobertura generado por pytest-cov
sonar.python.coverage.reportPaths=coverage.xml
sonar.python.xunit.reportPath=test-results.xml